name: Renovate a new version
on:
  push:
    branches:
      - feat/add-react-layer

jobs:
  renovate:
    name: Renovate
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]')) &&
      !(github.event_name == 'pull_request' && contains(join(github.event.pull_request.title, github.event.pull_request.body), '[skip ci]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run renovate
        uses: renovatebot/github-action@v32.0.1
        with:
          configurationFile: ./renovate.config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          GIT_AUTHOR: ${{ secrets.GIT_AUTHOR }}
